### ISSUE TITLE
iisNode , Socket.IO and Hapi.JS - Can't Find /socket.io/socket.io.js

### ISSUE THREAD

**Issue by AsimRamay** [tjanczuk/iisnode#475]
hi i'm new to Nodejs ,
trying to setup socket.io after completing a Hapi JS tutorial 
no errors seem to be occurring however the serving isn't serving the:
/socket.io/socket.io.js
file 
however Hapi JS api is still working perfectly and all other includes 

contents of my files are as follows:

[Console]
Server running at: socket:\\.\pipe\bef8a2e4-1e76-4039-b582-75d95d7b0990
Connected with Database

[web.config]
<?xml version="1.0" encoding="utf-8"?>
 
<configuration>
    <appSettings>
        
        
        <add key="virtualDirPath" value="" />
    </appSettings>
 
    <system.webServer>
        
        <staticContent>
          
        </staticContent>
 
        <modules runAllManagedModulesForAllRequests="false" />
 
        <iisnode
            node_env="%node_env%"
            nodeProcessCountPerApplication="1"
            maxConcurrentRequestsPerProcess="1024"
            maxNamedPipeConnectionRetry="100"
            namedPipeConnectionRetryDelay="250"
            maxNamedPipeConnectionPoolSize="512"
            maxNamedPipePooledConnectionAge="30000"
            asyncCompletionThreadCount="0"
            initialRequestBufferSize="4096"
            maxRequestBufferSize="65536"
            uncFileChangesPollingInterval="5000"
            gracefulShutdownTimeout="60000"
            loggingEnabled="true"
            logDirectory="iisnode"
            debuggingEnabled="true"
            debugHeaderEnabled="false"
            debuggerPortRange="5058-6058"
            debuggerPathSegment="debug"
            maxLogFileSizeInKB="128"
            maxTotalLogFileSizeInKB="1024"
            maxLogFiles="20"
            devErrorsEnabled="true"
            flushResponse="false"
            enableXFF="false"
            promoteServerVars=""
            configOverrides="iisnode.yml"
            watchedFiles="web.config;*.js"                    
            nodeProcessCommandLine="C:\Program Files\nodejs\node.exe" />

    
    <handlers>
      
         <add name="iisnode" path="server.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^server.js\/debug[\/]?" />
        </rule>

        
        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="server.js"/>
        </rule>
      </rules>
    </rewrite>
        <directoryBrowse enabled="false" />
  </system.webServer>
 
</configuration>

[Server.js]

'use strict';

const Hapi = require('hapi');
const path = require('path');
const mysql = require('mysql');

// Configure MySQL parameters
const connection      =         mysql.createConnection({
        host        :         "nodejs.internix.com.au",
        user        :         "******",
        password    :         "*******",
        database     :         "**********"
});

// connect to MySQL
connection.connect(function(error){
  if(error)
    {
       console.log("Problem with MySQL"+error);
    }
  else
    {
      console.log("Connected with Database");
    }
});

// Create a server with a host and port
const server = new Hapi.Server();
server.connection({ 
    host: 'nodejs.internix.com.au', 
    port: process.env.PORT
});

const io = require('socket.io')(server.listener);

server.register(require('inert'),  function(err) {
	if (err) {
		throw err;
	}
});

server.register(require('vision'),  function(err) {
	if (err) {
		throw err;
	}
});

// Add the routes
server.route({
    method: 'GET',
    path: '/hapijs/',
    handler: function (request, reply) {
        reply.view('index', {name: 'Jon'});
    }
});

server.route({
    method: 'GET',
    path: '/hapijs/user/{userName}',
    handler: function (request, reply) {
	var names = encodeURIComponent(request.params.userName)
        reply.view('user', {names: names});
    }
});

server.route({
    method: 'GET',
    path: '/hapijs/socketio/',
    handler: function (request, reply) {
	var src = ('/socket.io/socket.io.js')
        reply.view('socketio', {src: src});
    }
});

server.route({
    method: 'GET',
    path: '/hapijs/google.png',
    handler: function (request, reply) {
        reply.file('/hapijs/google.png');
    }
});

server.route({
    method: 'GET',
    path: '/hapijs/{name}',
    handler: function (request, reply) {
        reply('Hello, ' + encodeURIComponent(request.params.name) + '!');
    }
});

server.route({
    method: 'GET',
    path: '/hapijs/db/',
    handler: function (request, reply) {
	connection.query('SELECT * FROM people', function(err, rows, fields) {
		if (err) throw err;
		reply('The name is: '+ rows[0].Name);
	});
    }
});

// Add the veiws
server.views({
	engines: {
		html: require('handlebars')
	},
	relativeTo: __dirname,
	path: 'templates'
});

// Start the server
server.start((err) => {

    if (err) {
        throw err;
    }
    console.log('Server running at:', server.info.uri);
});

io.on('connection', function () {
io.set("transports", ["xhr-polling"]);
io.set("polling duration", 10);
});

io.on('connection', function (socket) {
  socket.emit('news', { hello: 'world' });
  socket.on('my other event', function (data) {
    console.log(data);
  });
});

**Comment by AsimRamay** [comment]
Fixed

**Comment by AsimRamay** [comment]
Fixed#475

**Comment by gundambandai** [comment]
Hi @AsimRamay, Have you fixed your problem, I'm also trying to use socket.io ver2.0.3 with iisnode, but still can't find the socket.io/socket.io. js even though did exactly what you did.
The error is : "Uncaught SyntaxError: Unexpected token <", Can you help me?

**Comment by AsimRamay** [comment]
it would be much easier to see the problem if you could post the code snippet your using , as all the Uncaught SyntaxError: Unexpected token tells me is that there is a syntax problem i.e. something like Math.max(2, 42) which is correct vs Math.max(2, 42,); which is wrong

**Comment by ves-krd** [comment]
@AsimRamay What did you web.config look like?

I keep getting 404 transport=polling errors with socketio.

Another question, what exactly is `path: '/hapijs/socket.io'` pointing to?  The socket.io.js file?

My folder structure is:

    public
      socketio
        socket.io.js
    app.js

**Comment by AsimRamay** [comment]
@ves-krd 

my web.config was as follows 

`<?xml version="1.0" encoding="utf-8"?>
 
<configuration>
    <appSettings>
        
        
        <add key="virtualDirPath" value="" />
    </appSettings>
 
    <system.webServer>
        
        <staticContent>
          
        </staticContent>
 
        <modules runAllManagedModulesForAllRequests="false" />
 
        <iisnode
            node_env="%node_env%"
            nodeProcessCountPerApplication="1"
            maxConcurrentRequestsPerProcess="1024"
            maxNamedPipeConnectionRetry="100"
            namedPipeConnectionRetryDelay="250"
            maxNamedPipeConnectionPoolSize="512"
            maxNamedPipePooledConnectionAge="30000"
            asyncCompletionThreadCount="0"
            initialRequestBufferSize="4096"
            maxRequestBufferSize="65536"
            uncFileChangesPollingInterval="5000"
            gracefulShutdownTimeout="60000"
            loggingEnabled="true"
            logDirectory="iisnode"
            debuggingEnabled="true"
            debugHeaderEnabled="false"
            debuggerPortRange="5058-6058"
            debuggerPathSegment="debug"
            maxLogFileSizeInKB="128"
            maxTotalLogFileSizeInKB="1024"
            maxLogFiles="20"
            devErrorsEnabled="true"
            flushResponse="false"
            enableXFF="false"
            promoteServerVars=""
            configOverrides="iisnode.yml"
            watchedFiles="web.config;*.js"                    
            nodeProcessCommandLine="C:\Program Files\nodejs\node.exe" />

    
    <handlers>
      
         <add name="iisnode" path="server.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^server.js\/debug[\/]?" />
        </rule>

        
        <rule name="StaticContent">
          <action type="Rewrite" url="public{REQUEST_URI}"/>
        </rule>

        
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
          </conditions>
          <action type="Rewrite" url="server.js"/>
        </rule>
                <rule name="SocketIO" patternSyntax="ECMAScript">
                  <match url="socket.io" />
                  <action type="Rewrite" url="server.js"/>
                </rule>
      </rules>
    </rewrite>
      <security>
        <requestFiltering>
          <hiddenSegments>
            <add segment="node_modules" />
          </hiddenSegments>
        </requestFiltering>
      </security> 
        <directoryBrowse enabled="false" />
  </system.webServer>
 
</configuration>`

`/hapijs/socket.io` points to where the socket.io file is served on live this depends on your configuration, mine wasn't served at the root of the domain but a subfolder in the domain, its good to point to this file either way as it minimises error caused by relative pathing in nodejs (as served location is like a mini sandbox in a way)
i.e. 
public
  Hapijs(app root)
    socket.io.js
    web.config

**Comment by ves-krd** [comment]
@AsimRamay Awesome, thank you.  I have everything up and running now, except POST requests aren't working... any ideas there?

Also, I don't know how to find the logs from the node process.  There should be some errors somewhere but I checked the documentation and the directories they suggest have nothing.

**Comment by AsimRamay** [comment]
as long as logging is enabled and log dir is set to default should show up in same folder as the js file as per documentation 

'if your application is at http://foo.com/bar.js, logs will be accessible at http://foo.com/iisnode;'

works for me this way so not sure what exactly is wrong there for you 

as for post requests make sure they are enabled in your iis website (by default they should be but its not always the case) i.e.

'''
If you are using IIS 6 and lower:

From inside the IIS management screen right click on your website or virtual directory. Go to Properties then go to the Home Directory or Virtual Directory tab and click on the Configuration button. From there you can add/update extensions and what Verbs are accepted.

If you are using IIS 7:

From inside the IIS management screen click on Handler Mappings. You can add by clicking the links on the right side or double-click on an item to edit it.
'''
as per https://stackoverflow.com/questions/3472429/how-do-i-configure-iis-to-accept-post-requests
